In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [23]:
i = np.arange(1, 21)
a = 2 ** i / i
a

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [24]:
i = np.arange(0, 6)
a = 0.1 ** (3 * i) * 0.2 ** (4 * i)
a.sum()

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

https://pythonworld.ru/numpy/100-exercises.html

1

In [37]:
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

2

In [3]:
zeros = np.zeros((8,8))
np.where(np.indices(zeros.shape).sum(axis=0)%2, zeros, 1)

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

3

In [132]:
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [33]:
X = np.random.random((5, 2))
# a = np.array([[1, -1], [2, 4]])
u, p = sp.linalg.polar(X)

In [35]:
X, u, p

(array([[0.93885727, 0.04806344],
        [0.64743459, 0.09021671],
        [0.70794849, 0.46024467],
        [0.15432393, 0.463041  ],
        [0.09730158, 0.47839068]]), array([[ 0.74304406, -0.1880315 ],
        [ 0.49692608, -0.0506376 ],
        [ 0.44532016,  0.44533553],
        [-0.00128107,  0.59933143],
        [-0.05136441,  0.63604882]]), array([[1.32940765, 0.26033508],
        [0.26033508, 0.77315235]]))

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [50]:
X = np.random.random((10, 10))
ind = np.unravel_index(np.argmax(X), np.shape(X))
X[ind]

0.9967230173404253

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [97]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
X[np.linalg.norm(X - y, axis = 1).argmin()]

array([0.68332421, 0.6602582 ])

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [103]:
x = np.linspace(-3, 3, 100)

In [104]:
np.piecewise(x, [x < 0, (0 <= x) * (x <= 2), x >= 2], [
    lambda x: x**2 + 2*x + 6,
    lambda x: x+6,
    lambda x: x**2 + 4*x - 4
])

array([ 9.        ,  8.76124885,  8.52984389,  8.30578512,  8.08907254,
        7.87970615,  7.67768595,  7.48301194,  7.29568411,  7.11570248,
        6.94306703,  6.77777778,  6.61983471,  6.46923783,  6.32598714,
        6.19008264,  6.06152433,  5.94031221,  5.82644628,  5.71992654,
        5.62075298,  5.52892562,  5.44444444,  5.36730946,  5.29752066,
        5.23507805,  5.17998163,  5.1322314 ,  5.09182736,  5.05876951,
        5.03305785,  5.01469238,  5.00367309,  5.        ,  5.00367309,
        5.01469238,  5.03305785,  5.05876951,  5.09182736,  5.1322314 ,
        5.17998163,  5.23507805,  5.29752066,  5.36730946,  5.44444444,
        5.52892562,  5.62075298,  5.71992654,  5.82644628,  5.94031221,
        6.03030303,  6.09090909,  6.15151515,  6.21212121,  6.27272727,
        6.33333333,  6.39393939,  6.45454545,  6.51515152,  6.57575758,
        6.63636364,  6.6969697 ,  6.75757576,  6.81818182,  6.87878788,
        6.93939394,  7.        ,  7.06060606,  7.12121212,  7.18

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [79]:
X = np.random.random((10, 10))
(X - X.mean(axis = 1).reshape((10, 1))).mean(axis = 1)

array([-5.55111512e-17, -9.99200722e-17,  1.11022302e-17, -2.22044605e-17,
        6.66133815e-17, -4.44089210e-17, -2.22044605e-17, -1.11022302e-16,
        2.22044605e-17, -4.44089210e-17])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [84]:
X = np.random.normal(loc=5, scale=2., size=1000)
X.mean(), X.var()

(4.994152705316059, 3.80647309928487)

**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [138]:
np.indices([5, 5]).sum(axis=0)%5

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]], dtype=int32)

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [201]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0 
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 4, 0, 0, 4]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [228]:
def sample_new(x, c):
    assert len(x) > 0
    
    rand = np.random.random(c) * np.sum(x)     
    matr = (x @ np.triu(np.ones(5))).reshape((5, 1)) 
    print(rand)
    dif = rand - matr
    
    answ = np.where(dif < 0, dif, -np.inf).argmax(axis = 0)
    
    return answ
sample_new([50, 3, 1, 7, 20], 5)    

[ 9.18332218 39.15403536 65.71685341 24.89528249  9.43194895]


array([0, 0, 4, 0, 0], dtype=int64)